apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect
  labels:
    app: debezium-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels:
        app: debezium-connect
    spec:
      containers:
      - name: connect
        image: jcmunuera/my-kafka-connect-debezium:latest
        command: ["/bin/bash", "-c"]
        args: ["/etc/confluent/docker/run"]
        ports:
        - containerPort: 8083
        env:
        - name: CONNECT_GROUP_ID
          value: "connect-cluster"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "connect-configs"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "connect-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "connect-status"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
          value: "false"
        - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
          value: "false"
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE
          value: "false"
        - name: CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE
          value: "false"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/java,/usr/share/confluent-hub-components"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "debezium-connect"
        - name: CONNECT_REST_PORT
          value: "8083"
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "my-kafka.default.svc.cluster.local:9092"
        - name: CONNECT_SASL_MECHANISM
          value: "SCRAM-SHA-256"
        - name: CONNECT_SECURITY_PROTOCOL
          value: "SASL_PLAINTEXT"
        - name: CONNECT_SASL_JAAS_CONFIG
          value: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"user1\" password=\"XKmY4LUimm\";"
        - name: CONNECT_CONSUMER_SASL_MECHANISM
          value: "SCRAM-SHA-256"
        - name: CONNECT_CONSUMER_SECURITY_PROTOCOL
          value: "SASL_PLAINTEXT"
        - name: CONNECT_CONSUMER_SASL_JAAS_CONFIG
          value: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"user1\" password=\"XKmY4LUimm\";"
        - name: CONNECT_PRODUCER_SASL_MECHANISM
          value: "SCRAM-SHA-256"
        - name: CONNECT_PRODUCER_SECURITY_PROTOCOL
          value: "SASL_PLAINTEXT"
        - name: CONNECT_PRODUCER_SASL_JAAS_CONFIG
          value: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"user1\" password=\"XKmY4LUimm\";"
        - name: JAVA_TOOL_OPTIONS
          value: "-Djava.security.auth.login.config=/etc/kafka/secrets/jaas.conf"
        volumeMounts:
        - name: jaas-config
          mountPath: /etc/kafka/secrets/
          readOnly: true
      volumes:
      - name: jaas-config
        configMap:
          name: kafka-connect-jaas-config