apiVersion: v1
kind: Pod
metadata:
  name: kafka-topic-creator
  labels:
    app: kafka-topic-creator
spec:
  containers:
  - name: kafka-client
    image: confluentinc/cp-kafka:7.6.0
    command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    env:
    - name: KAFKA_BROKER_ADDR
      value: "my-kafka.default.svc.cluster.local:9092"
  restartPolicy: Never
