apiVersion: v1
kind: Pod
metadata:
  name: temp-kafka-client
  labels:
    app: temp-kafka-client
spec:
  containers:
  - name: kafka-client
    image: confluentinc/cp-kafka:7.6.0
    command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    env:
    - name: KAFKA_OPTS
      value: "-Djava.security.auth.login.config=/etc/kafka/jaas.conf"
    - name: KAFKA_BROKER_ADDR
      value: "my-kafka.default.svc.cluster.local:9092"
    volumeMounts:
    - name: jaas-config
      mountPath: /etc/kafka/
      readOnly: true
  volumes:
  - name: jaas-config
    secret:
      secretName: kafka-jaas-config
  restartPolicy: Never
